//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loginAbstract.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSULTA
    {
        public Nullable<int> HASH { get; set; }
        public string FECHA { get; set; }
        public string HORA { get; set; }
        public string DNI { get; set; }
        public string REFERENCIA { get; set; }
        public string PRECIO_U { get; set; }
        public string CANTIDAD { get; set; }
        public string SUBTOTAL { get; set; }
    }
}
