//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loginAbstract.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS
    {
        public string PRODUCTO { get; set; }
        public string REFERENCIA { get; set; }
        public int PRECIO { get; set; }
        public string CATEGORIA { get; set; }
    }
}
