USE [master]
GO
/****** Object:  Database [ABSTRACT]    Script Date: 15/02/2022 2:51:42 p. m. ******/
CREATE DATABASE [ABSTRACT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'REGISTRO_ABSTRACT', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\REGISTRO_ABSTRACT.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'REGISTRO_ABSTRACT_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\REGISTRO_ABSTRACT_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ABSTRACT] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ABSTRACT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ABSTRACT] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ABSTRACT] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ABSTRACT] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ABSTRACT] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ABSTRACT] SET ARITHABORT OFF 
GO
ALTER DATABASE [ABSTRACT] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ABSTRACT] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ABSTRACT] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ABSTRACT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ABSTRACT] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ABSTRACT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ABSTRACT] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ABSTRACT] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ABSTRACT] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ABSTRACT] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ABSTRACT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ABSTRACT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ABSTRACT] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ABSTRACT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ABSTRACT] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ABSTRACT] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ABSTRACT] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ABSTRACT] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ABSTRACT] SET  MULTI_USER 
GO
ALTER DATABASE [ABSTRACT] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ABSTRACT] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ABSTRACT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ABSTRACT] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ABSTRACT] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ABSTRACT] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ABSTRACT] SET QUERY_STORE = OFF
GO
USE [ABSTRACT]
GO
/****** Object:  Table [dbo].[CLIENTE]    Script Date: 15/02/2022 2:51:42 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTE](
	[NAME] [varchar](max) NOT NULL,
	[DNI_TYPE] [varchar](max) NOT NULL,
	[DNI] [int] NOT NULL,
 CONSTRAINT [PK_CLIENTE] PRIMARY KEY CLUSTERED 
(
	[DNI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONSULTA]    Script Date: 15/02/2022 2:51:42 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONSULTA](
	[HASH] [int] NULL,
	[FECHA] [nchar](10) NULL,
	[HORA] [nchar](10) NULL,
	[DNI] [nchar](10) NULL,
	[REFERENCIA] [nchar](10) NOT NULL,
	[PRECIO_U] [nchar](10) NOT NULL,
	[CANTIDAD] [nchar](10) NOT NULL,
	[SUBTOTAL] [nchar](10) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOGIN]    Script Date: 15/02/2022 2:51:42 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOGIN](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USER] [varchar](max) NOT NULL,
	[PASSWORD] [varchar](max) NULL,
	[EMAIL] [varchar](max) NULL,
 CONSTRAINT [PK_LOGIN] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCTOS]    Script Date: 15/02/2022 2:51:42 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTOS](
	[PRODUCTO] [nvarchar](max) NOT NULL,
	[REFERENCIA] [nvarchar](max) NOT NULL,
	[PRECIO] [int] NOT NULL,
	[CATEGORIA] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RECORDAR]    Script Date: 15/02/2022 2:51:42 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RECORDAR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[REGISTRO] [varchar](max) NOT NULL,
	[USER] [varchar](max) NULL,
	[PASSWORD] [varchar](max) NULL,
	[ONECERO] [int] NULL,
 CONSTRAINT [PK_RECORDAR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[CLIENTE] ([NAME], [DNI_TYPE], [DNI]) VALUES (N'SOFIA ECHAVARRIA MONTOYA', N'T.I', 1020105341)
GO
INSERT [dbo].[CLIENTE] ([NAME], [DNI_TYPE], [DNI]) VALUES (N'SANTIAGO GIL FRANCO', N'T.I', 1033177340)
GO
SET IDENTITY_INSERT [dbo].[LOGIN] ON 
GO
INSERT [dbo].[LOGIN] ([ID], [USER], [PASSWORD], [EMAIL]) VALUES (1, N'admin', N'curso123', N'passiflora.freelance@gmail.com')
GO
INSERT [dbo].[LOGIN] ([ID], [USER], [PASSWORD], [EMAIL]) VALUES (1004, N'ADMIN', N'123', N'correodeprueba@gmail.com')
GO
INSERT [dbo].[LOGIN] ([ID], [USER], [PASSWORD], [EMAIL]) VALUES (1005, N'fds', N'fsdf', N'dsf')
GO
SET IDENTITY_INSERT [dbo].[LOGIN] OFF
GO
INSERT [dbo].[PRODUCTOS] ([PRODUCTO], [REFERENCIA], [PRECIO], [CATEGORIA]) VALUES (N'Camisa Silk Robe', N'CW10', 10000, N'CAMISAS')
GO
INSERT [dbo].[PRODUCTOS] ([PRODUCTO], [REFERENCIA], [PRECIO], [CATEGORIA]) VALUES (N'Camisa David Belly ', N'CW20', 40000, N'CAMISAS')
GO
INSERT [dbo].[PRODUCTOS] ([PRODUCTO], [REFERENCIA], [PRECIO], [CATEGORIA]) VALUES (N'Camisa Nude Back', N'CW30', 40000, N'CAMISAS')
GO
INSERT [dbo].[PRODUCTOS] ([PRODUCTO], [REFERENCIA], [PRECIO], [CATEGORIA]) VALUES (N'Camisa Holding Leg', N'CW40', 40000, N'CAMISAS')
GO
INSERT [dbo].[PRODUCTOS] ([PRODUCTO], [REFERENCIA], [PRECIO], [CATEGORIA]) VALUES (N'Camisa Silk Robe Black', N'CB10', 40000, N'CAMISAS')
GO
INSERT [dbo].[PRODUCTOS] ([PRODUCTO], [REFERENCIA], [PRECIO], [CATEGORIA]) VALUES (N'Camisa David Belly Black', N'CB20', 40000, N'CAMISAS')
GO
INSERT [dbo].[PRODUCTOS] ([PRODUCTO], [REFERENCIA], [PRECIO], [CATEGORIA]) VALUES (N'Camisa Nude Back Black', N'CB30', 40000, N'CAMISAS')
GO
INSERT [dbo].[PRODUCTOS] ([PRODUCTO], [REFERENCIA], [PRECIO], [CATEGORIA]) VALUES (N'Camisa Holding Leg Black', N'CB40', 40000, N'CAMISAS')
GO
SET IDENTITY_INSERT [dbo].[RECORDAR] ON 
GO
INSERT [dbo].[RECORDAR] ([ID], [REGISTRO], [USER], [PASSWORD], [ONECERO]) VALUES (1, N'YES', N'admin', N'curso123', 0)
GO
SET IDENTITY_INSERT [dbo].[RECORDAR] OFF
GO
USE [master]
GO
ALTER DATABASE [ABSTRACT] SET  READ_WRITE 
GO
